### ISSUE TITLE
The inference problem of single verifier

### ISSUE THREAD

**Issue by hhy-huang** [Jiuzhouh/PiVe#3]
Hi, thank you very much for your wonderful work. However, during my implementation, I found there is no inference code within the single verifier folder, which only consists the finetuning codes.

Could you please provide the inference code of single verifier module? Thank you very much.

**Comment by Jiuzhouh** [comment]
Hi, I just uploaded the inference script, you could run a command like this when you finish the training.
`./run_inference.sh t5-large outputs/t5_large_only_one_error/val_avg_bleu=17.9400-step_count=3.ckpt 0`

**Comment by hhy-huang** [comment]
> Hi, I just uploaded the inference script, you could run a command like this when you finish the training. `./run_inference.sh t5-large outputs/t5_large_only_one_error/val_avg_bleu=17.9400-step_count=3.ckpt 0`

Thank you for your prompt response!
